// <auto-generated />
using System;
using CR_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CR_Proiect.Migrations
{
    [DbContext(typeof(CR_ProiectContext))]
    [Migration("20231219172940_remodel")]
    partial class remodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CR_Proiect.Models.Biserica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegeID")
                        .HasColumnType("int");

                    b.Property<int?>("ReginaID")
                        .HasColumnType("int");

                    b.Property<string>("Religie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegeID");

                    b.HasIndex("ReginaID");

                    b.ToTable("Biserica");
                });

            modelBuilder.Entity("CR_Proiect.Models.Rege", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rege");
                });

            modelBuilder.Entity("CR_Proiect.Models.Regina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Regina");
                });

            modelBuilder.Entity("CR_Proiect.Models.Tara", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("BisericaID")
                        .HasColumnType("int");

                    b.Property<string>("Capitala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suprafata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BisericaID");

                    b.ToTable("Tara");
                });

            modelBuilder.Entity("CR_Proiect.Models.Biserica", b =>
                {
                    b.HasOne("CR_Proiect.Models.Rege", "Rege")
                        .WithMany("Biserica")
                        .HasForeignKey("RegeID");

                    b.HasOne("CR_Proiect.Models.Regina", "Regina")
                        .WithMany("Biserica")
                        .HasForeignKey("ReginaID");

                    b.Navigation("Rege");

                    b.Navigation("Regina");
                });

            modelBuilder.Entity("CR_Proiect.Models.Tara", b =>
                {
                    b.HasOne("CR_Proiect.Models.Biserica", "Biserica")
                        .WithMany("Tara")
                        .HasForeignKey("BisericaID");

                    b.Navigation("Biserica");
                });

            modelBuilder.Entity("CR_Proiect.Models.Biserica", b =>
                {
                    b.Navigation("Tara");
                });

            modelBuilder.Entity("CR_Proiect.Models.Rege", b =>
                {
                    b.Navigation("Biserica");
                });

            modelBuilder.Entity("CR_Proiect.Models.Regina", b =>
                {
                    b.Navigation("Biserica");
                });
#pragma warning restore 612, 618
        }
    }
}
